# -*- coding: utf-8 -*-
"""seasonal_agriculture.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AHVYHZBd6jPSYKj9aQGuvKB9SJZCmM8d
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""**import different Libraries**

Uplode Dataset
"""

from google.colab import files

uploaded = files.upload()

"""Read Dataset"""

df = pd.read_csv("seasonal_agriculture_performance_dataset.csv")

"""First 5 Rows"""

df.head()

"""Last 5 Rows"""

df.tail()

"""How many row and colum check"""

df.shape

"""Column Names"""

df.columns

"""Data Types Check"""

df.dtypes

"""Dataset Information"""

df.info()

"""Categorical Summary (means describe state,crop,and season)"""

df.describe(include='object')

"""Check missing Value"""

df.isnull().sum()

"""Check Duplicate Records"""

df.duplicated().sum()

"""Remove Duplicate Records"""

df = df.drop_duplicates()

"""Unique Values in Each Column"""

df.nunique()

"""Season Values(This code counts the number of records for each season) and how many season are there"""

df["Season"].unique()

df["Season"].value_counts()

"""State Distribution"""

df["State"].value_counts()

"""Crop Distribution check"""

df["Crop"].value_counts()

"""Check Statistical Summary of Numerical Data"""

df.describe().T

"""Create Clean Dataset"""

clean_data = df.copy()

"""Season Distribuation (This chart shows the number of records available for each season in the dataset. It helps identify which season has the highest and lowest number of agricultural records.)"""

plt.figure(figsize=(8,5))
sns.countplot(data=df, x='Season')

plt.title("Distribution of Seasons")
plt.xlabel("Season")
plt.ylabel("Count")

plt.show()

"""Crop Distribution(This chart displays the top 10 most frequently grown crops in the dataset. It helps identify the most common crops cultivated by farmers.)"""

top_crop = df["Crop"].value_counts().head(10)

plt.figure(figsize=(10,5))
sns.barplot(x=top_crop.index, y=top_crop.values)

plt.title("Top 10 Crops")
plt.xlabel("Crop")
plt.ylabel("Count")

plt.xticks(rotation=45)

plt.show()

"""State Distribution(This graph shows the top 10 states with the highest number of agricultural records in the dataset.)"""

top_state = df["State"].value_counts().head(10)

plt.figure(figsize=(10,5))
sns.barplot(x=top_state.index, y=top_state.values)

plt.title("Top 10 States")
plt.xlabel("State")
plt.ylabel("Count")

plt.xticks(rotation=45)

plt.show()

"""Rainfall Distribution(This histogram shows how rainfall values are distributed. It helps determine whether rainfall is evenly distributed or concentrated within a particular range.)

"""

plt.figure(figsize=(8,5))

plt.hist(df["Rainfall_mm"], bins=30)

plt.title("Rainfall Distribution")
plt.xlabel("Rainfall (mm)")
plt.ylabel("Frequency")

plt.show()

"""Temperature Distribution(This histogram graph the distribution of average temperature values across the dataset.)"""

plt.figure(figsize=(8,5))

plt.hist(df["Avg_Temperature_C"], bins=30)

plt.title("Average Temperature Distribution")
plt.xlabel("Temperature (°C)")
plt.ylabel("Frequency")

plt.show()

"""Humidity Distribution(This chart represents the distribution of humidity values recorded in the agricultural dataset.)

"""

plt.figure(figsize=(8,5))

plt.hist(df["Humidity_pct"], bins=30)

plt.title("Humidity Distribution")
plt.xlabel("Humidity (%)")
plt.ylabel("Frequency")

plt.show()

Soil pH check(This graph shows the distribution of soil pH values, helping us understand soil conditions across different farms.)

plt.figure(figsize=(8,5))

plt.hist(df["Soil_pH"], bins=30)

plt.title("Soil pH Distribution")
plt.xlabel("Soil pH")
plt.ylabel("Frequency")

plt.show()

"""Profit check(This graph shows how profit values are distributed among different agricultural records.)"""

plt.figure(figsize=(8,5))

plt.hist(df["Profit_INR"], bins=30)

plt.title("Profit Distribution")
plt.xlabel("Profit (INR)")
plt.ylabel("Frequency")

plt.show()

"""Revenue check(This histogram graph  the check  of revenue generated from agricultural activities.)"""

plt.figure(figsize=(8,5))

plt.hist(df["Revenue_INR"], bins=30)

plt.title("Revenue Distribution")
plt.xlabel("Revenue (INR)")
plt.ylabel("Frequency")

plt.show()

"""Season vs Average Profit:-This bar chart compares the average profit earned in each season. It helps identify which season generates the highest and lowest profit."""

plt.figure(figsize=(8,5))

sns.barplot(data=df, x="Season", y="Profit_INR")

plt.title("Average Profit by Season")
plt.xlabel("Season")
plt.ylabel("Average Profit (INR)")

plt.show()

"""Check Season vs Average Revenue:-This chart compares the average revenue across different seasons and helps determine the most profitable season."""

plt.figure(figsize=(8,5))

sns.barplot(data=df, x="Season", y="Revenue_INR")

plt.title("Average Revenue by Season")
plt.xlabel("Season")
plt.ylabel("Average Revenue (INR)")

plt.show()

"""Check Season vs Crop Yield:-This visualization shows the average crop yield in each season and helps identify the most productive season."""

plt.figure(figsize=(8,5))

sns.barplot(data=df, x="Season", y="Yield_Tonnes_Ha")

plt.title("Average Crop Yield by Season")
plt.xlabel("Season")
plt.ylabel("Yield (Tonnes/Ha)")

plt.show()

"""Check Crop vs Average Profit (Top 10 Crops):-"""

top_crop = df["Crop"].value_counts().head(10).index

crop_df = df[df["Crop"].isin(top_crop)]

plt.figure(figsize=(12,6))

sns.barplot(data=crop_df,
            x="Crop",
            y="Profit_INR")

plt.xticks(rotation=45)

plt.title("Average Profit of Top 10 Crops")

plt.show()

"""Check Rainfall vs Yield:-This scatter plot shows the relationship between rainfall and crop yield. It helps determine whether rainfall has any impact on agricultural production."""

plt.figure(figsize=(8,5))

sns.scatterplot(data=df,
                x="Rainfall_mm",
                y="Yield_Tonnes_Ha")

plt.title("Rainfall vs Crop Yield")
plt.xlabel("Rainfall (mm)")
plt.ylabel("Yield (Tonnes/Ha)")

plt.show()

"""Check Temperature vs Yield:-This graph helps analyze whether average temperature influences crop yield."""

plt.figure(figsize=(8,5))

sns.scatterplot(data=df,
                x="Avg_Temperature_C",
                y="Yield_Tonnes_Ha")

plt.title("Temperature vs Crop Yield")
plt.xlabel("Temperature (°C)")
plt.ylabel("Yield (Tonnes/Ha)")

plt.show()

"""Check Water Used vs Production"""

plt.figure(figsize=(8,5))

sns.scatterplot(data=df,
                x="Water_Used_m3",
                y="Production_Tonnes")

plt.title("Water Used vs Production")
plt.xlabel("Water Used (m³)")
plt.ylabel("Production (Tonnes)")

plt.show()

"""Check Season vs Water Usage:-This box plot compares water usage across different seasons and helps identify seasonal variations."""

plt.figure(figsize=(8,5))

sns.boxplot(data=df,
            x="Season",
            y="Water_Used_m3")

plt.title("Water Usage by Season")

plt.show()

"""Top 10 States by Average Profit:-This chart identifies the top 10 states with the highest average agricultural profit."""

state_profit = df.groupby("State")["Profit_INR"].mean().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,5))

sns.barplot(x=state_profit.index, y=state_profit.values)

plt.title("Top 10 States by Average Profit")
plt.xlabel("State")
plt.ylabel("Average Profit (INR)")

plt.xticks(rotation=45)

plt.show()

"""Check Average Revenue by Season:-This pie chart represents the percentage share of average revenue contributed by each season."""

season_revenue = df.groupby("Season")["Revenue_INR"].mean()

plt.figure(figsize=(8,5))

plt.pie(season_revenue,
        labels=season_revenue.index,
        autopct="%1.1f%%",
        startangle=90)

plt.title("Revenue Share by Season")

plt.show()

"""Water Efficiency Distribution:-This histogram shows the distribution of water efficiency values among farms."""

plt.figure(figsize=(8,5))

plt.hist(df["Water_Efficiency_t_per_1000m3"], bins=30)

plt.title("Water Efficiency Distribution")
plt.xlabel("Water Efficiency")
plt.ylabel("Frequency")

plt.show()

"""Profit vs Revenue:-This scatter plot shows the relationship between revenue and profit."""

plt.figure(figsize=(8,5))

sns.scatterplot(data=df,
                x="Revenue_INR",
                y="Profit_INR")

plt.title("Revenue vs Profit")

plt.show()

"""Average Profit by State:-This analysis identifies the average agricultural profit earned in each state. It helps determine the most profitable states."""

state_profit = df.groupby("State")["Profit_INR"].mean().sort_values(ascending=False)

print(state_profit)

"""Average Yield by Crop:-This analysis identifies the crops with the highest average yield."""

crop_yield = df.groupby("Crop")["Yield_Tonnes_Ha"].mean().sort_values(ascending=False)

print(crop_yield)

"""Average Revenue by Season:-This analysis compares the average revenue generated in different agricultural seasons."""

season_revenue = df.groupby("Season")["Revenue_INR"].mean()

print(season_revenue)

"""Dashboard :-This dashboard summarizes four important analyses:
(1)Profit by Season
(2)Yield by Season
(3)Rainfall vs Yield
(4)Revenue vs Profit
"""

plt.figure(figsize=(16,10))

# 1
plt.subplot(2,2,1)
sns.barplot(data=df,x="Season",y="Profit_INR")
plt.title("Profit by Season")

#2
plt.subplot(2,2,2)
sns.barplot(data=df,x="Season",y="Yield_Tonnes_Ha")
plt.title("Yield by Season")

#3
plt.subplot(2,2,3)
sns.scatterplot(data=df,x="Rainfall_mm",y="Yield_Tonnes_Ha")
plt.title("Rainfall vs Yield")

#4
plt.subplot(2,2,4)
sns.scatterplot(data=df,x="Revenue_INR",y="Profit_INR")
plt.title("Revenue vs Profit")

plt.tight_layout()

plt.show()